### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by Stakhan** [nittanygeek/LiDAR-Importer#10]
Hi!

I'm trying to install the addon but somehow I can't manage to install laspy on the Python interpreter used by Blender, I keep getting the `ModuleNotFoundError: No module named 'laspy'` error...

## Local specs
+ Windows 10
+ Blender 3.3

## What I tried
**1. Identifying the Python interpreter used and installing laspy into it**
I have a lot of different python executable on my Windows system (through the use of Anaconda) so I identified the one used by Blender:
```
>>> import sys
>>> sys.executable
'C:\\Program Files\\Blender Foundation\\Blender 3.3\\3.3\\python\\bin\\python.EXE'
```
Then I installed laspy into that interpreter:
```
"C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\bin\python.exe" -m pip install laspy
```

**2. Using the startup scripts**
I prepared a conda environment with the Python version used by Blender 3.3 (which is 3.10.2) and installed laspy into it:
```bash
conda create -n laspy_py3.10 python=3.10.2
conda activate laspy_py3.10
pip install laspy
```
Then added a file called `anaconda_deps.py` into `C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\startup` with the following content:
```python
import sys
sys.path.append('C:\\Users\\EAL\\Anaconda3\\envs\\laspy_py3.10\\lib\\site-packages')
def register():
    print("Added anaconda library to path")
```

None of the two solutions above solve the issue and I keep getting a `ModuleNotFoundError`.

Looking forward to your ideas on where the issue could be coming from.

EDIT: added local specs

**Comment by Poommmm** [comment]
I am also having this problem - cant someone write a tutorial on how to do this - i've never written a script , but i need this add on to work - i downloaded 3.6 because its already inside that build but the .las add on still doesnt work and is asking for laspy.

**Comment by nittanygeek** [comment]
I've made some changes to the code recently and tested it on my own machine with the latest version of Blender.  Let me know if it's working now.

**Comment by nittanygeek** [comment]
Closing issue, as new install instructions are provided in the README along with rewrite of importer code.

**Comment by Poommmm** [comment]
You amazing chap - I can’t wait to get home I am cycling back 50 miles :)
Thank you so much x

**Comment by Poommmm** [comment]
This may take me some time because i've never added any code or tried
scripting , but still thank you so much.
very kind.
