### ISSUE TITLE
Make creation of Pull requests possible

### ISSUE THREAD

**Issue by dreisicht** [nittanygeek/LiDAR-Importer#13]
I went over the script to improve performance significtly, I just can't send a PR since branching is disabled.
For reference the updated script is here: [__init___.txt](https://github.com/nittanygeek/LiDAR-Importer/files/13247659/__init___.txt)

**Comment by nittanygeek** [comment]
You should be able to send a PR to master, I've had several in the past do this without issue.  I'll look more into making a dev branch at some point if needed.

**Comment by dreisicht** [comment]
Sorry, I wasn't sufficient with GitHub and didn't know that I had to fork the repo first.
