### ISSUE TITLE
Module 'laspy' not found

### ISSUE THREAD

**Issue by andrew-plowright** [nittanygeek/LiDAR-Importer#5]
Hello. Trying to install this add-on, although it looks like laspy needs to be installed separately? Would it be possible to get instructions on how to do this?

Thanks!

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Andrew\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\__init___.py", line 41, in <module>
    import laspy
ModuleNotFoundError: No module named 'laspy'
```

**Comment by mmuulinn** [comment]
I'm having the same issue, and not able to activate the Add-On.  Anyone know of a fix?

**Comment by nittanygeek** [comment]
When you install laspy, does it work?  Install instructions are on their website: https://pypi.org/project/laspy/
```
pip install laspy
```

**Comment by DeluxeMonster** [comment]
https://blender.stackexchange.com/questions/41258/install-python-module-for-blender

**Comment by Hellreaver** [comment]
If it doesn't work with pip you may have python 3+ which uses pip3.

**Comment by nittanygeek** [comment]
Updated the code and it should be working now.
